### PR TITLE
Added cross-compilation options found in documentation

### PR DESCRIPTION
**Pull request by as-shura**
Fix for the only part which cause problem on ARM32/ARM64.

Added NODE_OPTIONS environment variable since boards are limited with memory. This can prevent Javascript heap memory errors.

https://github.com/dotenx/dotenx/issues/321

### CODE REVIEW

**Comment by mkamrani** [comment]
Thanks for PR, I'll run your branch locally today before the review.

**Comment by Hojjat-1** [comment]
Hi @as-shura first i should appreciation for your contribution. Thank you.
Your changes on Dockerfile of ao-api is useful but why you change postgresql and redis configs? It seems you are trying to fix multiple issue in one PR. Please remove these changes (redis, postgresql, max-heap-size) and also define default values for new parameters in Dockerfile of ao-api.

**Comment by as-shura** [comment]
> Hi @as-shura first i should appreciation for your contribution. Thank you. Your changes on Dockerfile of ao-api is useful but why you change postgresql and redis configs? It seems you are trying to fix multiple issue in one PR. Please remove these changes (redis, postgresql, max-heap-size) and also define default values for new parameters in Dockerfile of ao-api.

Sorry I didn't realized that I pushed things related to FerretDB sitting on top of PostgresSQL and also to allow external connection from outside to manage the instance with pgAdmin 4.

**Comment by Hojjat-1** [comment]
Ok, Thanks for reverting something. I will test your branch and let you know any updates.

**Review by Hojjat-1 — APPROVED** [review]

**Pull request merged**
